/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.analysis;

import lexing.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTBeginComment(TBeginComment node);
    void caseTInComment(TInComment node);
    void caseTStar(TStar node);
    void caseTEndComment(TEndComment node);
    void caseTBegin(TBegin node);
    void caseTOmega(TOmega node);
    void caseTInt(TInt node);
    void caseTString(TString node);
    void caseTBoolean(TBoolean node);
    void caseTDeclare(TDeclare node);
    void caseTPrint(TPrint node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTIf(TIf node);
    void caseTFi(TFi node);
    void caseTWhile(TWhile node);
    void caseTWend(TWend node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMultiply(TMultiply node);
    void caseTDivide(TDivide node);
    void caseTLessthan(TLessthan node);
    void caseTGreaterthan(TGreaterthan node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTIncrement(TIncrement node);
    void caseTDecrement(TDecrement node);
    void caseTAssign(TAssign node);
    void caseTIdentifier(TIdentifier node);
    void caseTNumber(TNumber node);
    void caseTSpace(TSpace node);
    void caseTUnknown(TUnknown node);
    void caseEOF(EOF node);
}
