/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilerHW4.node;

import compilerHW4.analysis.*;

@SuppressWarnings("nls")
public final class TDecrement extends Token
{
    public TDecrement()
    {
        super.setText("levelDown");
    }

    public TDecrement(int line, int pos)
    {
        super.setText("levelDown");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDecrement(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecrement(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDecrement text.");
    }
}
