/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilerHW4.node;

import compilerHW4.analysis.*;

@SuppressWarnings("nls")
public final class TIncrement extends Token
{
    public TIncrement()
    {
        super.setText("levelUp");
    }

    public TIncrement(int line, int pos)
    {
        super.setText("levelUp");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIncrement(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIncrement(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIncrement text.");
    }
}
