/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexing.node;

import lexing.analysis.*;

@SuppressWarnings("nls")
public final class TPlus extends Token
{
    public TPlus()
    {
        super.setText("loot");
    }

    public TPlus(int line, int pos)
    {
        super.setText("loot");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPlus(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPlus(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPlus text.");
    }
}
