/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilerHW4.node;

import compilerHW4.analysis.*;

@SuppressWarnings("nls")
public final class TString extends Token
{
    public TString()
    {
        super.setText("tome");
    }

    public TString(int line, int pos)
    {
        super.setText("tome");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TString(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTString(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TString text.");
    }
}
