/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilerHW4.node;

import compilerHW4.analysis.Analysis;

@SuppressWarnings("nls")
public final class TWend extends Token
{
    public TWend()
    {
        super.setText("end_contract");
    }

    public TWend(int line, int pos)
    {
        super.setText("end_contract");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TWend(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTWend(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TWend text.");
    }
}
